# GitHub actions - Create Tesseract installer for Windows

name: Cross build for Windows

on:
  push:
    branches:
    - 'windows'

  # Trigger workflow in GitHub web frontend or from API.
  workflow_dispatch:
    inputs:
      targets:
        description: 'Target operating system'
        required: true
        default: 'Windows (64 bit)'
        type: choice
        options:
          - 'Windows (32 bit)'
          - 'Windows (64 bit)'

jobs:
  build32:
    # Disable 32 bit builds.
    if: github.repository == '_UB-Mannheim/tesseract'
    runs-on: [ubuntu-24.04]
    steps:
    - uses: actions/checkout@v4
    - name: Build Tesseract installer (32 bit)
      run: .github/workflows/build.sh i686
    - uses: actions/upload-artifact@v4
      with:
        name: Tesseract Installer for Windows (32 bit)
        path: dist

  build64:
    if: github.repository == 'UB-Mannheim/tesseract'
    runs-on: [ubuntu-24.04]
    steps:
    - uses: actions/checkout@v4
    - name: Build Tesseract installer (64 bit)
      run: .github/workflows/build.sh x86_64
    - uses: actions/upload-artifact@v4
      with:
        name: Tesseract Installer for Windows (64 bit)
        path: dist
